#!/usr/bin/with-contenv bash

echo "--Check-HW-transcoding--"
if hash nvidia-smi 2>/dev/null; then
    echo "Runtime detected"
    echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader)"
    echo "Capabilities: ${NVIDIA_DRIVER_CAPABILITIES} Devices: ${NVIDIA_VISIBLE_DEVICES}"
else
    echo "Runtime not detected"
fi

echo "--Debug--"
echo "TZ: ${TZ}"