# syntax = docker/dockerfile-upstream

ARG BIN_STAGE
FROM ${BIN_STAGE:-${BASE}:binaries} AS BinStage

ARG BASE_IMAGE
FROM ${BASE_IMAGE:-ubuntu@sha256:3013b0d761d4bad6ff16dd2805887a2f2c3fc140d6206086698b5c3e44e0f7fe}

COPY --from=BinStage ["/", "/"]
ENV DEBIAN_FRONTEND=noninteractive NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"

RUN ffmpeg --help
RUN ffprobe --help
RUN ccextractor --help
RUN HandBrakeCLI --help